- azure-pipelines.yml
This change is a first attempt at setting up an Azure Pipeline for N64-UNFLoader. I've followed the `UNFLoader_Linux` steps as a guideline for setting up the necessary dependencies and then installing it.
I'm unable to test the pipeline at the moment, but all of the steps worked on my MacBook Pro (non-retina, mid-2012) with macOS Catalina 10.15.7. I'd assume any Intel Mac should work the same. Not sure about Apple silicon though.
The pipeline stage does the following:
1. Downloads the driver helpers
2. Installs the driver helpers with the `installer` command
3. Downloads the D2XX drivers from the [FTDI website](https://ftdichip.com/drivers/d2xx-drivers/)
4. Unzips the D2XX drivers, showing a [DMG image](https://en.wikipedia.org/wiki/Apple_Disk_Image).
5. Mounts the `release` DMG image …
> First attempt at setting up a macOS Azure build

- UNFLoader/debug.cpp
This is a bit of a nitpick change, but I figured I'd put up a PR to help keep the UNFLoader working on a variety of compilers and platforms.
I was compiling on macOS with default system version of `g++` (eg: Apple clang version 12.0.0 (clang-1200.0.32.29)). The compiler gave me the following warning in `debug.cpp`.
```bash
$ make
g++ -D LINUX -o UNFLoader main.cpp helper.cpp device.cpp debug.cpp device_64drive.cpp device_everdrive.cpp device_sc64.cpp Include/lodepng.cpp -lncurses -lftd2xx -lpthread -Wl,-rpath /usr/local/lib -L/usr/local/lib
debug.cpp:329:23: warning: multiple unsequenced modifications to 'blinker' [-Wunsequenced]
blinker = (blinker++) % (1+BLINKRATE * 2);
~         ^
1 warning generated.
```
I doubt the lack of [sequence …
> Add sequence point to `++` operation in debug.cpp

- UNFLoader/device_64drive.cpp
- UNFLoader/device_sc64.cpp
When I compile `UNFLoader` on macOS with Apple Clang 12, I get the following compiler warnings
```
g++ -D LINUX -o UNFLoader main.cpp helper.cpp device.cpp debug.cpp device_64drive.cpp device_everdrive.cpp device_sc64.cpp Include/lodepng.cpp -lncurses -lftd2xx -lpthread -Wl,-rpath /usr/local/lib -L/usr/local/lib
device_64drive.cpp:93:22: warning: passing an object that undergoes default argument promotion to 'va_start' has undefined behavior [-Wvarargs]
va_start(params, numparams);
^
device_64drive.cpp:88:78: note: parameter of type 'u8' (aka 'unsigned char') is declared here
void device_sendcmd_64drive(ftdi_context_t* cart, u8 command, bool reply, u8 numparams, ...)
^
1 warning generated.
device_sc64.cpp:108:22: warning: passing an object that undergoes default argument promotion to …
```
> 64Drive/SummerCart64: Add C11 UB fix for va_start

- USB+Debug Library/usb.c
This change allows the application on N64 not to block even if UNFLoader is stopped.
Since usb.c is being vendored into libdragon, this change is important to open up for different tools that have a different approach compared to UNFLoader. While UNFLoader is a all-in-one tool to upload + debug N64 application, one can imagine some simpler tool that simply connects to the USB streams to monitor logs sent with the same protocol (a log viewer). Such an application might be started and stopped at any time during the N64 application lifetime, and we don't want the application to break whenever the tool Is stopped.
> Add a timeout to usb_64drive_waitidle

- UNFLoader/device_64drive.cpp
- UNFLoader/device_everdrive.cpp
- UNFLoader/device_sc64.cpp
I noticed that if I tried to load a ROM with UNFLoader when the EverDrive OS was not running, I would get a Segmentation Fault: 
```
UNFLoader
--------------------------------------------
Cobbled together by Buu342
Compiled on Mar  1 2021
Debug mode enabled.
Attempting flashcart autodetection.
Error: No flashcart detected. Are you running sudo?
Segmentation fault: 11
```
This PR attempts to fix that, by setting the cart handle to zero whenever `FT_Close` is called.
The PR also includes whitespace corrections for the files that are touched. I'm happy to remove those if you think that they are too much of a distraction from the salient changes in this PR.
> Fix segmentation fault when loading ROM while flash drive OS is not running

- Examples/Libultra/1. Hello World/usb.c
- Examples/Libultra/2. Thread Faults/usb.c
- Examples/Libultra/3. USB Read/usb.c
- Examples/Libultra/4. Command Interpreter/usb.c
- USB+Debug Library/usb.c
As discussed in https://github.com/buu342/N64-UNFLoader/issues/63
While diffing each copy of usb.c, I noticed that D64_POLLTIME was different for example 3. I've changed that to be consistent with the primary copy of `USB+Debug Library/usb.c` but I can change that back if it was different for a reason.
> Memory alignment fix for usb_everdrive_writereg

- USB+Debug Library/usb.c
This prevents it from indefinitely waiting if the usb buffer is full.
> Add timeout for the usb_everdrive_usbbusy method

- Examples/Libdragon/1. Hello World/usb.c
- Examples/Libdragon/2. USB Read/usb.c
- Examples/Libdragon/3. Command Interpreter/usb.c
- Examples/Libultra/1. Hello World/usb.c
- Examples/Libultra/2. Thread Faults/usb.c
- Examples/Libultra/3. USB Read/usb.c
- Examples/Libultra/4. Command Interpreter/usb.c
- USB+Debug Library/usb.c
Hello again! After my earlier changes to resolve memory alignment issues, I noticed that on very rare occasions, my code would crash in similar ways. After a lot of trial and error, I found three cases where DMA reads/writes needed to be aligned to 16-byte boundaries rather than 8-bytes. I don't entirely understand why this was necessary, but I have found N64 documentation that recommends doing this.
From http://n64devkit.square7.ch/n64man/os/osPiStartDma.htm:
> The PI device address (devAddr) must be 2-byte aligned. The RDRAM virtual address (vAddr) must be 8-byte aligned, but for OS_READ DMA operations, a stricter alignment is recommended. See OS_DCACHE_ROUNDUP_ADDR for a description of the problems that can occur when transfers are not an integral number of cache lines.
I followed that …
> Align Everdrive reads/writes to 16 byte boundaries

- USB+Debug Library/usb.c
- This is not something it should do. The rom will already initialize
these as it needs them to be. Everdive will pif boot into the loaded
rom and IPL will set the values from the rom header as usual. usb.c
should not manipulate them implicitly.
> Remove the part that re-initializes some of PI regs

- .gitignore
- UNFLoader/Makefile
This PR edits the Makefile for building UNFLoader under MacOS/Linux to be more "intelligent" in how it does things
Previously, the makefile would always rebuild the app by running g++ with every single code file at the same time, so all files would be recompiled regardless if any changes had actually been made to the codebase
Now, each codefile is built seperately, and linked together at the end to form the executable. Additonally, `clean`, `install`, and `uninstall` targets have been added.
`clean` deletes built artifacts like the app and object files.
`install` installs UNFLoader to `/usr/local/bin`, allowing it to be used system-wide.
`uninstall` will delete UNFLoader from `/usr/local/bin`, if it exists.
> Refactor makefile

- UNFLoader/helper.cpp
This fixes the usage of variadic arguments in some functions in helper.cpp (for example __pdprint).
The `va_list` was forwarded to multiple functions (`vw_printw` and `vfprintf`), which is not actually allowed and only worked by chance on some implementations. On linux+gcc for example the debug log would get created, but nothing got written to it.
The solution is to call `va_start` multiple times (once for each usage), or copy the `va_list` with `va_copy`.
> Fix writing to debug log file on some systems

- UNFLoader/device.cpp
I added two checks about reading a rom file, on fread and ftell operations
#94
#94
After these changes my jank bindings (the code in issue) still don't work (as expected) but at least the SC64 bootloader is safe for this specific occurrence
> Some more error checking on opening a ROM file

- USB+Debug Library/usb.c
Small change that gets rid of ambiguous timeout durations defined in loop iterations. Instead it uses coprocessor C0 COUNT register to get accurate timing.
No related issue
To remove timeout duration ambiguity
On libdragon build with SC64 flashcart. 64drive and libultra testing would be welcome.
No screenshots
> USB library - define timeout duration in milliseconds

- USB+Debug Library/usb.c
Fixes `usb_everdrive_poll` so that it will always compute the correct packet size on compilers where the default signedness of `char` is signed, as is the case in the libdragon toolchain. See https://github.com/buu342/N64-UNFLoader/issues/112 for more specifics on why this doesn't work as-is.
https://github.com/buu342/N64-UNFLoader/issues/112
Sending packets of specific sizes over Everdrive USB to programs built with a compiler where `char` defaults to signed currently does not work. I ran into this while working on a project involving doing just that.
Previously, a packet of length 0x80 - 0xFF (inclusive) would appear to never arrive. After this change such packets arrive as expected.
> Fix `usb_everdrive_poll` for compilers using signed char

- UNFLoader/README.md
The system requirements section mentioned `install_linux.sh` which is a file that does not exist.
> docs: fix script name in linux system requirements

- UNFLoader/device.cpp
- UNFLoader/device.h
- UNFLoader/device_64drive.cpp
- UNFLoader/device_sc64.cpp
This gracefully handles custom IPL3 bootcodes such as those that can be forked from libdragon's open source one.
NOTE: this is currently untested
> Use the IPL2 checksum to decide which CIC to use.

- UNFLoader/Makefile
This adds a new variable to the Makefile, `PREFIX`, that can be set (either by editing the file or by using `make install PREFIX="a filesystem location"`) to specify the include path and install location in place of `/usr/local`.
No related issue
Currently, the Makefile provides no way to specify an install location without manually editing every instance of the default path in the file. This allows setting install locations other than `/usr/local` directly in the CLI, which can be useful in contexts such as software packaging.
This has been tested on EndeavourOS Linux. Head into the UNFLoader source directory and run the following commands:
```sh
$ make
$ sudo make install PREFIX=/usr
```
This should install the UNFLoader executable to `/usr/bin/UNFLoader`.
> Add PREFIX variable to Makefile

- USB+Debug Library/debug.c
1. Add two breakpoints
2. Remove two breakpoints
The second breakpoint will fail to be removed.
The second breakpoint is failing to be removed because the underlying instruction is still pointing the the old index (2), meanwhile the record in the table has shifted left.
The shift left is unnecessary, since addbreakpoint already scans the table. Can remove it entirely and fix the code.
> Remove shift left code from removebreakpoint

- UNFLoader/helper.cpp
When terminate is called, assume it's an error and exit with an appropriate termination state.
Otherwise it's not possible to use unfloader in a pipeline.
> Exit with error status.

- USB+Debug Library/usb.c
All X cards identify themselves as 0xED640013, but not all of them have a USB unit. This commit checks if the USB device reports to be powered, which seems to sufficient to detect the X5.
> usb_findcart: correctly detect Everdrive X-cards without USB

- Examples/Libultra/1. Hello World/usb.c
- Examples/Libultra/2. Thread Faults/usb.c
- Examples/Libultra/3. USB Read/usb.c
- Examples/Libultra/4. Command Interpreter/usb.c
- UNFLoader/debug.cpp
- UNFLoader/term.cpp
- USB+Debug Library/usb.c
I came across some race conditions when trying this out with Libultra + EverDrive X7 (OS version 3.08).
I am trying to upload a ROM (~24 MB) to debug with GDB. Due to the ROM size, uploading can take some time. During this time, UNFLoader would sometimes crash (#130). On successful upload, GDB could rarely connect (#131).
**PC Side:**
* Multiple threads can read/modify the terminal `local_mesgqueue` at once
* Multiple threads can read/modify the debug `local_mesgqueue` at once
I was seeing crashes because of this, but it's possible for more subtle effects such as corrupt data. Fixed by protecting access using mutexes.
**Flashcart Side (Libultra Only):**
The debugger code relies on the USB thread having the highest priority so other threads don't interrupt it during reads/writes. However, …
> Thread synchronization for terminal, and debug communication

- Examples/Libdragon/1. Hello World/debug.c
- Examples/Libdragon/3. Command Interpreter/debug.c
- Examples/Libultra/1. Hello World/debug.c
- Examples/Libultra/2. Thread Faults/debug.c
- Examples/Libultra/4. Command Interpreter/debug.c
- USB+Debug Library/debug.c
In `debug.c`, `debug_rdb_qsupported()` [does not copy the null terminator](https://github.com/buu342/N64-UNFLoader/blob/725a07ae34b870fe04f6116c483cfb82ea87e8b1/USB%2BDebug%20Library/debug.c#L1439) to the response.
Depending on the previous buffer contents, sometimes everything is fine, but other times breakpoints don't work since GDB doesn't know the target supports software breakpoints (invalid qSupported response).
I noticed the other responses are null terminated so did the same here.
Without the fix, I observed the following warning in GDB:
```
warning: unrecognized item "swbreak+<garbage>" in "qSupported" response
```
(`<garbage>` depends on previous `debug_buffer` contents)
Sometimes everything was fine, other times I encountered the breakpoint issues mentioned above.
With the fix, …
> Qsupported response

- UNFLoader/main.cpp
This commit fixes an issue where bits 0-3 in the "savetype" field in the ED header weren't discarded to determine the save type.
none lol
It fixes an annoying bug
Tested on the SummerCart64 with manually set savetype field in the hex editor.
> Mask save type field when extracting data from the ED ROM header format

- UNFLoader/FlashcartLib_Dynamic.vcxproj
- UNFLoader/FlashcartLib_Dynamic.vcxproj.filters
- UNFLoader/FlashcartLib_Static.vcxproj
- UNFLoader/FlashcartLib_Static.vcxproj.filters
- UNFLoader/Makefile
- UNFLoader/UNFLoader.vcxproj
- UNFLoader/device.cpp
- UNFLoader/device.h
- UNFLoader/device_gopher64.cpp
- UNFLoader/device_gopher64.h
- UNFLoader/helper.cpp
- UNFLoader/main.cpp
This is a companion to this PR in Gopher64: https://github.com/gopher64/gopher64/pull/526
I have only tested this on Linux so far. The debug example ROM (Hello World and USB Read) work without issue. However, the NetLib ROMs don't seem to work correctly yet, for example:
---
This driver works using TCP. Gopher64 starts a TCP server, and UNFLoader communicates with that TCP server. ROM uploading and regular read/writes are supported.
I wanted to add Netlib support to Gopher64 so that the potential was there to play with physical consoles.
> Add gopher64 support
